### ISSUE TITLE
Non-static method STS\UploadServer\UploadServer::route() cannot be called statically

### ISSUE THREAD

**Issue by MrMooky** [stechstudio/laravel-upload-server#1]
I added `UploadServer::route()` to my `web.php` routes file and receive this error:

> Non-static method STS\UploadServer\UploadServer::route() cannot be called statically

Am I missing something?

**Comment by jszobody** [comment]
I think it's supposed to be the facade getting called, not `STS\UploadServer\UploadServer`. Are you specifying that full path in your web.php routes file, or is it being imported at the top?

Remove that path or import if so, and just use the root `UploadServer::route()` facade.

I probably should change the name of the UploadServer class itself to avoid that confusion.

**Comment by MrMooky** [comment]
I imported it at the top. Removing the import gives me the red underlines. When importing by namespace, only `STS\UploadServer\UploadServer` is found. Nothing else. But manually using `use STS\UploadServer\UploadServerFacade;` does not work either.

<img width="217" alt="Screenshot 2021-11-30 at 13 52 11" src="https://user-images.githubusercontent.com/3603346/144050703-d54aba3b-1a89-47fd-bbe4-edcc84964d0f.png">

**Comment by jszobody** [comment]
It's been a bit since I set up this package from scratch in an app, so I just went and created a fresh Laravel app to test it out.

I changed the web.php routes file to be nothing but this:

```php
<?php

use Illuminate\Support\Facades\Route;

UploadServer::route();
```

And when I do `php artisan route:list` I see the route that was generated:

```
upload  php artisan route:list
+--------+------------------------+---------------------+---------------+------------------------------------------------------------+------------------------------------------+
| Domain | Method                 | URI                 | Name          | Action                                                     | Middleware                               |
+--------+------------------------+---------------------+---------------+------------------------------------------------------------+------------------------------------------+
|        | GET|HEAD               | api/user            |               | Closure                                                    | api                                      |
|        |                        |                     |               |                                                            | App\Http\Middleware\Authenticate:sanctum |
|        | GET|HEAD               | sanctum/csrf-cookie |               | Laravel\Sanctum\Http\Controllers\CsrfCookieController@show | web                                      |
|        | POST|DELETE|HEAD|PATCH | upload-server       | upload-server | STS\UploadServer\Servers\FilePondServer@handle             | web                                      |
+--------+------------------------+---------------------+---------------+------------------------------------------------------------+------------------------------------------+
```

That seems to just work as expected. Not sure why it's failing for you.

Note the alias is setup in the composer.json file:

https://github.com/stechstudio/laravel-upload-server/blob/master/composer.json#L51

Your IDE won't know how to import it, and I'm not surprised that there would be red underlines. Nevertheless, it _should_ still work, just like you see in my code above.

**Comment by jszobody** [comment]
I also changed it to the full Facade path:

```
STS\UploadServer\UploadServerFacade::route();
```

That worked for me as well. 

Let me know if you're still having issues? I wonder if composer or artisan needs something cleared. I've had others mention before with our packages that aliases/facades sometimes aren't available initially, I'm not sure why.

**Comment by MrMooky** [comment]
Seems to work that way. Thank you very much! :)
